name: update manifest
on:
  schedule: # for scheduling to work this file must be in the default branch
    - cron: "0 0 * * *" # run every day
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/flathub-infra/flatpak-external-data-checker:latest
        with:
          args: --edit-only org.freedesktop.Sdk.Extension.fish.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
